table:
  - column:
      - allowNull: ''
        dotIndex: ''
        length: ''
        name: ''
        type: ''
    comment: ''
    name: ''
    primaryKey:
      - allowNull: ''
        dotIndex: ''
        length: ''
        name: ''
        type: ''
